### ISSUE TITLE
Prometheus Server is Failing to Start

### ISSUE THREAD

**Issue by dlx** [cncf/cross-cloud#27]
Prometheus Server is Failing to Start with error 

```
[dlx@W541 aws-mvci-stable]$ docker run -ti registry.cncf.ci/prometheus/prometheus:ci-v1.5.2.cd47ea7b.6027
panic: standard_init_linux.go:175: exec user process caused "no such file or directory" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "no such file or directory"

goroutine 1 [running, locked to thread]:
panic(0x7ddca0, 0xc820117c70)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8200ed2e8)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7ddca0, 0xc820117c70)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc8200ecbf8, 0xc8200220c8, 0xc8200ecd08)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820061630, 0x7fcf1a319728, 0xc820117c70)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc820080a00, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x7446a0, 0x8f09d0, 0x13, 0x839798, 0x4, 0xc8200ed268, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x7446a0, 0x8f09d0, 0x13, 0xc8200ed268, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x7446a0, 0x8f09d0, 0xc820080a00, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x83c628, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8cff80, 0x51, 0x0, ...)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001b00, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
	/go/src/github.com/opencontainers/runc/main.go:137 +0xe24
```

**Comment by dlx** [comment]
Looks like we need to build Prometheus as a static Binary to Fix
https://github.com/prometheus/prometheus/issues/2457

**Comment by zilman** [comment]
> Yes I've observed this as well, unfortunately the go compiler behaves differently when on OSX or linux. On OSX because there is no glibc to link to it compiles a binary that does not link to it, even when not explicitly disabling cgo. Then when you compile the same thing on linux there is a glibc available and so it links to it, and when you then put that binary in a container it doesn't work anymore.

**Comment by zilman** [comment]
https://github.com/prometheus/promu/issues/60

> If you need a static binary I suggest you run promu crossbuild

**Comment by dlx** [comment]
Noticed about OSX upstream https://github.com/prometheus/prometheus/issues/2457#issuecomment-283311996 we aren't using OSX though? 
Looking into promu cross-build.

**Comment by hh** [comment]
https://gitlab.cncf.ci/prometheus/prometheus/builds/6058
Adding ``` CGO_ENABLED=0```


```
# docker run -ti registry.cncf.ci/prometheus/prometheus:ci-v1.5.2.d419bced.6059
INFO[0000] Starting prometheus (version=1.5.2, branch=HEAD, revision=d419bcedb2d03dc855e753b5c6fdbb8ab11be07a)  source=main.go:75
INFO[0000] Build context (go=go1.8.1, user=root@runner-293dc831-project-20-concurrent-0, date=20170605-21:32:59)  source=main.go:76
INFO[0000] Loading configuration file /etc/prometheus/prometheus.yml  source=main.go:248
INFO[0000] Loading series map and head chunks...         source=storage.go:373
INFO[0000] 0 series loaded.                              source=storage.go:378
INFO[0000] Starting target manager...                    source=targetmanager.go:61
INFO[0000] Listening on :9090                            source=web.go:259
```

**Comment by zilman** [comment]
[RFC: Prometheus component builds](https://docs.google.com/document/d/1Ql-f_aThl-2eB5v3QdKV_zgBdetLLbdxxChpy-TnWSE/edit#heading=h.nzgrhigme7z7) - not sure we should diverge.

**Comment by zilman** [comment]
Can't use promu crossbuild with the runners we have, this is fine for now. Closing.
